name: Deploy to Azure and Explore GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: Get response from Azure service
        id: azure-response
        run: |
          # Aqui podemos rodar qualquer comando do Azure CLI ou script que busque dados do serviço
          RESPONSE=$(az resource show --id "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProvider}/{resourceType}/{resourceName}" --query "properties" -o json)
          echo "Resposta do serviço Azure: $RESPONSE"
          echo "::set-output name=response::$RESPONSE"

      - name: Use response in next steps
        run: |
          echo "Usando a resposta: ${{ steps.azure-response.outputs.response }}"